fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    logrotate: "https://github.com/rodjek/puppet-logrotate.git"
  symlinks:
    "fluentd": "#{source_dir}"
